### PR TITLE
Update version

### PR DESCRIPTION
**Pull request by EcutDavid**
Support the merged PR #39 
And add issue/PR template

### CODE REVIEW

**Comment by EcutDavid** [comment]
Already singed, weird...

**Comment by obartra** [comment]
Did these changes get reverted? I don't see v0.4.0 published on npm or package.json on master

**Comment by misoguy** [comment]
I'm also curious about this. Why is the version not 0.4.0 here and on npm?

**Comment by obartra** [comment]
@d3viant0ne is working on it as part of webpack-contrib/i18n-webpack-plugin#41

He explained it on gitter as:
> they require a major and another major is being rolled in with it. That pull request merged in the wrong semver change and was rebased out.

**Comment by d3viant0ne** [comment]
@misoguy @obartra - I'm finishing webpack-contrib/i18n-webpack-plugin#41 up now. 

As I don't personally use this loader, I'm looking to get as many people as possible trying it out before something ends up in the dist-tag that doesn't work. @obartra has already volunteered, it would be great if I could get @misoguy to try it out as well.

No real functional changes, just a complete refactoring to employ current JavaScript language features to include ES modules ( defaulting to a cjs proxy ) as a part of an org wide conversion to `webpack-defaults`.

I'll tag both of you in the pull request in a couple of hours and get all of this out on an npm `beta` tag.

**Comment by d3viant0ne** [comment]
@misoguy - To the specific issue with this PR and to add to what @obartra said, the change that went into master ( and still is ) which prompted this version bump is not backwards compatible and would be breaking to anyone using `Webpack < 2.3 || Nodejs < 4.3` which is why this was rebased out and the change in master has been held back long enough for me to roll in the webpack-defaults changes which also requires a semver major.

**Comment by misoguy** [comment]
@d3viant0ne Understood, I'll try it out after 2 weeks since I'll be on my honeymoon for 2 weeks :)

**Pull request merged**
